from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from enum import Enum, auto


# Extraction Layer -----------------------------------------

@dataclass
class TextEntity:
    """
    Unified representation for extracted term
    """
    text: str                # normalized text content
    original_text: str       # original text content before normalization
    lemma: str               # lemma of term
    span: Tuple[int, int]    # start and end positions in the original text
    score: float             # candidate rating

    # context
    pos_tags: List[str] = field(default_factory=list)    # POS tags for the term tokens
    sentence: str = ""                                   # Sentence where the term occurs
    frequency: int = 1                                   # Frequency of the term in the document

    # metadata
    extractor_type: str = ""                                    # Which extractor produced this entity
    properties: Dict[str, Any] = field(default_factory=dict)    # Extra features (tf-idf, embedding, etc.)

    @property
    def normalized_form(self) -> str:
        return self.lemma.lower()


# Verification Layer -----------------------------------------

@dataclass(frozen=True)
class Entity:
    id:            str                                                   # unique identifier ("glossary:001", "ontology:1234", etc.)
    label:         str                                                   # "term", "concept", "entity", etc.
    synonyms:      List[str] = field(default_factory=list)               # list of synonymous names/labels for this entity
    relations:     Dict[str, List[str]] = field(default_factory=dict)    # relation type -> list of related entity ids
    definition:    Optional[str] = None                                  # textual definition or description of the entity
    source:        Optional[str] = None                                  # source of the entity (glossary name, ontology IRI, etc.)


class MatchStatus(Enum):

    MATCHED = auto()
    UNKNOWN = auto()
    AMBIGUOUS = auto()
    NEAR_MATCH = auto()


@dataclass(frozen=True)
class MatchResult:
    text_entity: TextEntity
    entity: Optional[Entity] = None
    confidence: float = 0.0
    status: MatchStatus = MatchStatus.UNKNOWN
    matched_synonym: Optional[str] = None


# Reporting Layer -----------------------------------------

class ReportType(str, Enum):
    """
    Types of reports that can be generated by the termlint pipeline
    """
    EXTRACTION = "extraction"              # extracted term candidates statistics
    PROCESSING = "processing"              # extracted and processed candidate statistics
    VERIFICATION = "verification"          # ontology coverage and matching statistics
    ONTOLOGY_UPDATE = "ontology_update"    # suggestions for ontology
    QUALITY_GATE = "quality_gate"          # CI/CD quality gate results (pass/fail)


@dataclass
class Report:
    """
    Standardized report format for termlint results, designed to be flexible for different report types.
    """
    report_type: ReportType

    # base metrics
    total_items: int
    processed_items: int

    # report type specific
    coverage_pct: Optional[float] = None
    unknown_terms: Optional[List[TextEntity]] = None
    suggested_entities: Optional[List[TextEntity]] = None
    matches: Optional[List[MatchResult]] = None
    quality_pass: Optional[bool] = None
    exit_code: Optional[int] = None

    # additional
    quality_score: Optional[float] = None
    raw_data: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert the report to a dictionary, excluding None values for cleaner output."""
        result = asdict(self)
        return {k: v for k, v in result.items() if v is not None}

    @property
    def is_success(self) -> bool:
        """Convenience property to check if the quality gate passed based on the quality_pass field."""
        return self.quality_pass is True


@dataclass
class ReportConfig:
    """
    Configuration for generating reports in the termlint pipeline,
    allowing users to specify which reports to include and how to export them.
    """
    include: List[ReportType] = field(default_factory=lambda: [ReportType.VERIFICATION])
    exporters: List[str] = field(default_factory=lambda: ["json"])
    output_dir: Path = field(default_factory=lambda: Path.cwd() / "reports/")
    quality_gates: Optional[Dict[str, Any]] = None


@dataclass
class QualityConfig:
    """
    """
    min_coverage: float = 90.
    max_unknown: int = 5
    min_quality_score: float = 0.8

    def check(self, reports: List[Report]) -> bool:
        """
        Check if the provided reports meet the quality gate criteria.
        """
        verification = next((r for r in reports if r.report_type == ReportType.VERIFICATION), None)
        if not verification or verification.coverage_pct is None:
            return False

        if verification.coverage_pct < self.min_coverage:
            return False

        unknown_count = len(verification.unknown_terms or [])
        return unknown_count <= self.max_unknown
